import { useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Bot,
  BookOpen,
  Shield,
  CheckCircle,
  XCircle,
  AlertTriangle,
  ArrowRight,
  Brain,
  FileCheck,
  GraduationCap,
  Sparkles,
  Users,
  Star,
  Lightbulb,
  Scale,
  Search,
  FileText,
  Cpu,
  Quote,
  ExternalLink,
  ChevronRight
} from "lucide-react";
import Layout from "@/components/layout/Layout";
import SEO from "@/components/SEO";
import FAQSchema from "@/components/schemas/FAQSchema";
import BreadcrumbSchema from "@/components/schemas/BreadcrumbSchema";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import Breadcrumbs from "@/components/ui/breadcrumbs";
import { aiReadinessQuestions, getAIReadinessLevel } from "@/data/aiPolicies";
import heroImage from "@/assets/blog/ai-academia-hub.jpg";

const faqs = [
  {
    question: "Can I use ChatGPT for my dissertation?",
    answer: "Yes, in most cases, but with important caveats. Most universities now allow limited AI use for tasks like brainstorming, grammar checking, and literature searching. However, using AI to generate content that you present as your own original work is typically prohibited. Always check your university's specific policy and disclose any AI assistance in your methodology section."
  },
  {
    question: "Do I need to disclose AI use in my dissertation?",
    answer: "Yes, the vast majority of universities now require disclosure of AI tool usage. This typically goes in your methodology section or acknowledgments. Some institutions have specific declaration forms. Our AI Policy Checker tool can tell you exactly what your university requires."
  },
  {
    question: "Will AI detection tools flag my work?",
    answer: "AI detection tools like Turnitin's AI detector look for patterns typical of AI-generated text. If you've used AI ethically (for editing, not content generation), you should have nothing to worry about. However, even heavily edited AI content may be flagged. The safest approach is to use AI as a thinking partner, not a writing replacement."
  },
  {
    question: "How do I cite ChatGPT or other AI tools?",
    answer: "Citation formats vary by style guide. APA 7th edition recommends citing AI as a software tool with the prompt used. MLA suggests treating it as a 'work generated by artificial intelligence.' Our Citing AI Guide provides templates for all major citation styles."
  },
  {
    question: "What AI tools are acceptable for dissertation research?",
    answer: "Most universities permit AI tools for: literature search (Elicit, Consensus), grammar checking (Grammarly), citation management, and data analysis assistance. Tools that generate substantial text content (ChatGPT for writing) are typically restricted. Always check your specific institution's guidelines."
  },
  {
    question: "Can my supervisor detect if I used AI?",
    answer: "Experienced supervisors often notice AI-generated content through stylistic inconsistencies, unusual phrasing, or content that doesn't match your previous writing. Additionally, many universities now use AI detection software. Transparency and disclosure are always the safest approach."
  }
];

const clearFramework = [
  {
    letter: "C",
    title: "Cite AI Contributions",
    description: "Always acknowledge AI tools in your methodology or acknowledgments section",
    icon: Quote
  },
  {
    letter: "L",
    title: "Limit to Appropriate Tasks",
    description: "Use AI for editing, searching, and brainstorming—not content generation",
    icon: Scale
  },
  {
    letter: "E",
    title: "Evaluate Outputs Critically",
    description: "Verify all AI-generated information against primary sources",
    icon: Search
  },
  {
    letter: "A",
    title: "Acknowledge in Methodology",
    description: "Include specific details about which tools you used and how",
    icon: FileText
  },
  {
    letter: "R",
    title: "Retain Human Authorship",
    description: "Ensure your core arguments and analysis remain your original work",
    icon: Brain
  }
];

const aiToolCategories = [
  {
    category: "Literature Search",
    status: "generally-allowed",
    tools: ["Elicit", "Consensus", "Semantic Scholar", "Connected Papers"],
    description: "AI-powered academic search engines help find relevant papers efficiently",
    bestPractice: "Cross-reference results with traditional databases like Web of Science"
  },
  {
    category: "Writing Assistance",
    status: "allowed-with-disclosure",
    tools: ["Grammarly", "ProWritingAid", "Hemingway Editor"],
    description: "Grammar and style checkers improve writing quality without generating content",
    bestPractice: "Disclose use in acknowledgments; ensure suggestions maintain your voice"
  },
  {
    category: "Data Analysis",
    status: "allowed-with-disclosure",
    tools: ["JASP", "Python/R with AI libraries", "ChatGPT for code help"],
    description: "AI can assist with statistical analysis and code generation",
    bestPractice: "Document all AI-assisted analysis steps in your methodology"
  },
  {
    category: "Content Generation",
    status: "restricted",
    tools: ["ChatGPT", "Claude", "Gemini", "Copilot"],
    description: "Using AI to generate dissertation content is typically prohibited",
    bestPractice: "Use only for brainstorming ideas you then develop independently"
  },
  {
    category: "Paraphrasing",
    status: "prohibited",
    tools: ["QuillBot", "Spinbot", "Paraphrasing tools"],
    description: "AI paraphrasing of sources can constitute academic misconduct",
    bestPractice: "Paraphrase manually and cite sources properly"
  }
];

const policyApproaches = [
  {
    type: "Full Restriction",
    prevalence: "Rare (~5%)",
    description: "No AI tools permitted for any academic work",
    color: "destructive"
  },
  {
    type: "Limited Use",
    prevalence: "Common (~25%)",
    description: "Only grammar/spelling tools allowed",
    color: "secondary"
  },
  {
    type: "Disclosed Use",
    prevalence: "Most Common (~60%)",
    description: "AI allowed with mandatory acknowledgment",
    color: "default"
  },
  {
    type: "Integrated Use",
    prevalence: "Growing (~10%)",
    description: "AI encouraged with specific guidelines",
    color: "outline"
  }
];

const AIAcademiaHub = () => {
  const [quizStep, setQuizStep] = useState(0);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [showResults, setShowResults] = useState(false);

  const handleAnswer = (questionId: number, score: number) => {
    setAnswers(prev => ({ ...prev, [questionId]: score }));
  };

  const calculateScore = () => {
    return Object.values(answers).reduce((sum, score) => sum + score, 0);
  };

  const nextQuestion = () => {
    if (quizStep < aiReadinessQuestions.length - 1) {
      setQuizStep(prev => prev + 1);
    } else {
      setShowResults(true);
    }
  };

  const resetQuiz = () => {
    setQuizStep(0);
    setAnswers({});
    setShowResults(false);
  };

  const result = showResults ? getAIReadinessLevel(calculateScore()) : null;

  return (
    <Layout>
      <SEO
        title="AI in Academia Hub | Ethical AI Use for Dissertations | DissertlyPro"
        description="Navigate AI in your dissertation with confidence. University AI policies, ethical frameworks, disclosure templates, and tools for responsible AI use in graduate research."
        canonical="https://dissertlypro.com/ai-academia"
        keywords={["AI in academia", "ChatGPT dissertation", "AI disclosure", "AI detection", "ethical AI use", "university AI policy", "cite ChatGPT", "AI academic integrity"]}
      />
      <FAQSchema faqs={faqs} />
      <BreadcrumbSchema
        items={[
          { name: "Home", url: "https://dissertlypro.com" },
          { name: "Resources", url: "https://dissertlypro.com/resources" },
          { name: "AI in Academia", url: "https://dissertlypro.com/ai-academia" }
        ]}
      />

      {/* Hero Section */}
      <section className="relative pt-8 pb-16 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-background to-background" />
        <div className="absolute top-20 left-1/4 w-72 h-72 bg-primary/10 rounded-full blur-3xl" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-accent/10 rounded-full blur-3xl" />

        <div className="container mx-auto max-w-6xl px-4 relative">
          <Breadcrumbs
            items={[
              { label: "Home", href: "/" },
              { label: "Resources", href: "/resources" },
              { label: "AI in Academia" }
            ]}
            className="mb-6"
          />

          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <Badge className="mb-4" variant="secondary">
                <Bot className="w-3 h-3 mr-1" />
                AI in Academic Research
              </Badge>
              <h1 className="text-4xl md:text-5xl font-bold mb-6 leading-tight">
                Navigating <span className="text-gradient-copper">AI</span> in Your Dissertation
              </h1>
              <p className="text-xl text-muted-foreground mb-8">
                Ethical frameworks, university policies, and practical tools for responsible 
                AI use in graduate research. Stay compliant and confident.
              </p>

              {/* Quick Stats */}
              <div className="grid grid-cols-3 gap-4 mb-8">
                <div className="text-center p-4 bg-card rounded-xl border">
                  <div className="text-2xl font-bold text-primary">85%</div>
                  <div className="text-xs text-muted-foreground">Universities have AI policies</div>
                </div>
                <div className="text-center p-4 bg-card rounded-xl border">
                  <div className="text-2xl font-bold text-primary">3x</div>
                  <div className="text-xs text-muted-foreground">Increase in AI disclosure requirements</div>
                </div>
                <div className="text-center p-4 bg-card rounded-xl border">
                  <div className="text-2xl font-bold text-primary">50+</div>
                  <div className="text-xs text-muted-foreground">University policies in our database</div>
                </div>
              </div>

              <div className="flex flex-wrap gap-4">
                <Button asChild size="lg">
                  <Link to="/tools/ai-policy-checker">
                    <Shield className="w-4 h-4 mr-2" />
                    Check Your University Policy
                  </Link>
                </Button>
                <Button asChild variant="outline" size="lg">
                  <Link to="#quiz">
                    <Brain className="w-4 h-4 mr-2" />
                    Take AI Readiness Quiz
                  </Link>
                </Button>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="relative hidden lg:block"
            >
              <img
                src={heroImage}
                alt="AI in academic research workspace"
                className="rounded-2xl shadow-2xl"
              />
              <div className="absolute -bottom-6 -left-6 bg-card p-4 rounded-xl shadow-lg border">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-green-500/10 rounded-full flex items-center justify-center">
                    <CheckCircle className="w-6 h-6 text-green-500" />
                  </div>
                  <div>
                    <div className="font-semibold">Ethical AI Use</div>
                    <div className="text-sm text-muted-foreground">Stay compliant & confident</div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* AI Readiness Quiz */}
      <section id="quiz" className="py-16 px-4 bg-muted/30">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <Badge className="mb-4" variant="outline">
              <Sparkles className="w-3 h-3 mr-1" />
              Self-Assessment
            </Badge>
            <h2 className="text-3xl font-bold mb-4">AI Readiness Quiz</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Assess your knowledge of AI policies and ethical use practices. 
              Get personalized recommendations based on your score.
            </p>
          </div>

          <Card className="max-w-2xl mx-auto">
            <CardContent className="p-8">
              {!showResults ? (
                <>
                  <div className="flex items-center justify-between mb-6">
                    <span className="text-sm text-muted-foreground">
                      Question {quizStep + 1} of {aiReadinessQuestions.length}
                    </span>
                    <span className="text-sm font-medium text-primary">
                      {Math.round(((quizStep + 1) / aiReadinessQuestions.length) * 100)}% Complete
                    </span>
                  </div>
                  <Progress value={((quizStep + 1) / aiReadinessQuestions.length) * 100} className="mb-8" />

                  <h3 className="text-xl font-semibold mb-6">
                    {aiReadinessQuestions[quizStep].question}
                  </h3>

                  <RadioGroup
                    value={answers[aiReadinessQuestions[quizStep].id]?.toString()}
                    onValueChange={(value) => handleAnswer(aiReadinessQuestions[quizStep].id, parseInt(value))}
                    className="space-y-3"
                  >
                    {aiReadinessQuestions[quizStep].options.map((option) => (
                      <div
                        key={option.value}
                        className="flex items-center space-x-3 p-4 rounded-lg border hover:bg-muted/50 cursor-pointer transition-colors"
                      >
                        <RadioGroupItem value={option.score.toString()} id={option.value} />
                        <Label htmlFor={option.value} className="flex-1 cursor-pointer">
                          {option.label}
                        </Label>
                      </div>
                    ))}
                  </RadioGroup>

                  <div className="flex justify-between mt-8">
                    <Button
                      variant="outline"
                      onClick={() => setQuizStep(prev => Math.max(0, prev - 1))}
                      disabled={quizStep === 0}
                    >
                      Previous
                    </Button>
                    <Button
                      onClick={nextQuestion}
                      disabled={answers[aiReadinessQuestions[quizStep].id] === undefined}
                    >
                      {quizStep === aiReadinessQuestions.length - 1 ? "See Results" : "Next"}
                      <ArrowRight className="w-4 h-4 ml-2" />
                    </Button>
                  </div>
                </>
              ) : (
                <div className="text-center">
                  <div className={`w-20 h-20 mx-auto rounded-full flex items-center justify-center mb-6 ${
                    result?.level === "Expert" ? "bg-green-500/10" :
                    result?.level === "Compliant" ? "bg-blue-500/10" :
                    result?.level === "Informed" ? "bg-yellow-500/10" : "bg-red-500/10"
                  }`}>
                    <GraduationCap className={`w-10 h-10 ${
                      result?.level === "Expert" ? "text-green-500" :
                      result?.level === "Compliant" ? "text-blue-500" :
                      result?.level === "Informed" ? "text-yellow-500" : "text-red-500"
                    }`} />
                  </div>
                  
                  <Badge className="mb-4" variant={
                    result?.level === "Expert" ? "default" :
                    result?.level === "Compliant" ? "secondary" :
                    result?.level === "Informed" ? "outline" : "destructive"
                  }>
                    {result?.level} Level
                  </Badge>
                  
                  <h3 className="text-2xl font-bold mb-4">
                    Your Score: {calculateScore()} / {aiReadinessQuestions.length * 3}
                  </h3>
                  
                  <p className="text-muted-foreground mb-6">
                    {result?.description}
                  </p>
                  
                  <div className="text-left bg-muted/50 rounded-lg p-6 mb-6">
                    <h4 className="font-semibold mb-3">Recommendations:</h4>
                    <ul className="space-y-2">
                      {result?.recommendations.map((rec, index) => (
                        <li key={index} className="flex items-start gap-2 text-sm">
                          <ChevronRight className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                          {rec}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="flex gap-4 justify-center">
                    <Button onClick={resetQuiz} variant="outline">
                      Retake Quiz
                    </Button>
                    <Button asChild>
                      <Link to="/tools/ai-policy-checker">
                        Check Your Policy
                        <ArrowRight className="w-4 h-4 ml-2" />
                      </Link>
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Understanding AI Policies */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <Badge className="mb-4" variant="outline">
              <FileCheck className="w-3 h-3 mr-1" />
              Policy Landscape
            </Badge>
            <h2 className="text-3xl font-bold mb-4">Understanding University AI Policies</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              University approaches to AI in academic work vary significantly. 
              Here's the current landscape.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
            {policyApproaches.map((approach, index) => (
              <motion.div
                key={approach.type}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className="h-full">
                  <CardHeader>
                    <div className="flex items-center justify-between mb-2">
                      <Badge variant={approach.color as "default" | "secondary" | "destructive" | "outline"}>
                        {approach.prevalence}
                      </Badge>
                    </div>
                    <CardTitle className="text-lg">{approach.type}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">{approach.description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>

          <div className="bg-gradient-to-r from-primary/10 to-accent/10 rounded-2xl p-8 text-center">
            <h3 className="text-2xl font-bold mb-4">Find Your University's Policy</h3>
            <p className="text-muted-foreground mb-6 max-w-xl mx-auto">
              Our AI Policy Checker covers 50+ universities across the UK, US, Australia, and Canada. 
              Get specific guidance for your institution.
            </p>
            <Button asChild size="lg">
              <Link to="/tools/ai-policy-checker">
                <Shield className="w-4 h-4 mr-2" />
                Use AI Policy Checker
                <ArrowRight className="w-4 h-4 ml-2" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* CLEAR Framework */}
      <section className="py-16 px-4 bg-muted/30">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <Badge className="mb-4" variant="outline">
              <Lightbulb className="w-3 h-3 mr-1" />
              Ethical Framework
            </Badge>
            <h2 className="text-3xl font-bold mb-4">The CLEAR Framework for Ethical AI Use</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              A simple, memorable framework for using AI responsibly in your dissertation.
            </p>
          </div>

          <div className="grid md:grid-cols-5 gap-6">
            {clearFramework.map((item, index) => (
              <motion.div
                key={item.letter}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className="h-full text-center hover:shadow-lg transition-shadow">
                  <CardHeader>
                    <div className="w-16 h-16 mx-auto bg-primary/10 rounded-full flex items-center justify-center mb-4">
                      <span className="text-3xl font-bold text-primary">{item.letter}</span>
                    </div>
                    <CardTitle className="text-lg">{item.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">{item.description}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* AI Tools for Research */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <Badge className="mb-4" variant="outline">
              <Cpu className="w-3 h-3 mr-1" />
              Tool Guide
            </Badge>
            <h2 className="text-3xl font-bold mb-4">AI Tools for Research: What's Allowed?</h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              A practical guide to which AI tools are typically permitted for dissertation work.
            </p>
          </div>

          <div className="space-y-6">
            {aiToolCategories.map((category, index) => (
              <motion.div
                key={category.category}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className="overflow-hidden">
                  <div className="flex flex-col md:flex-row">
                    <div className={`w-full md:w-48 p-6 flex items-center justify-center ${
                      category.status === "generally-allowed" ? "bg-green-500/10" :
                      category.status === "allowed-with-disclosure" ? "bg-yellow-500/10" :
                      category.status === "restricted" ? "bg-orange-500/10" : "bg-red-500/10"
                    }`}>
                      <div className="text-center">
                        {category.status === "generally-allowed" && <CheckCircle className="w-8 h-8 text-green-500 mx-auto mb-2" />}
                        {category.status === "allowed-with-disclosure" && <AlertTriangle className="w-8 h-8 text-yellow-500 mx-auto mb-2" />}
                        {category.status === "restricted" && <AlertTriangle className="w-8 h-8 text-orange-500 mx-auto mb-2" />}
                        {category.status === "prohibited" && <XCircle className="w-8 h-8 text-red-500 mx-auto mb-2" />}
                        <Badge variant={
                          category.status === "generally-allowed" ? "default" :
                          category.status === "allowed-with-disclosure" ? "secondary" :
                          category.status === "restricted" ? "outline" : "destructive"
                        }>
                          {category.status.replace(/-/g, " ").replace(/\b\w/g, l => l.toUpperCase())}
                        </Badge>
                      </div>
                    </div>
                    <div className="flex-1 p-6">
                      <h3 className="text-xl font-semibold mb-2">{category.category}</h3>
                      <p className="text-muted-foreground mb-4">{category.description}</p>
                      <div className="flex flex-wrap gap-2 mb-4">
                        {category.tools.map(tool => (
                          <Badge key={tool} variant="outline">{tool}</Badge>
                        ))}
                      </div>
                      <div className="text-sm bg-muted/50 p-3 rounded-lg">
                        <strong>Best Practice:</strong> {category.bestPractice}
                      </div>
                    </div>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Related Resources */}
      <section className="py-16 px-4 bg-muted/30">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">Explore AI Resources</h2>
            <p className="text-muted-foreground">Dive deeper into specific AI topics</p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            <Link to="/tools/ai-policy-checker" className="group">
              <Card className="h-full hover:shadow-lg transition-all hover:border-primary/50">
                <CardHeader>
                  <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                    <Shield className="w-6 h-6" />
                  </div>
                  <CardTitle className="text-lg group-hover:text-primary transition-colors">
                    AI Policy Checker
                  </CardTitle>
                  <CardDescription>
                    Find your university's AI policy and get disclosure templates
                  </CardDescription>
                </CardHeader>
              </Card>
            </Link>

            <Link to="/ai-detection-guide" className="group">
              <Card className="h-full hover:shadow-lg transition-all hover:border-primary/50">
                <CardHeader>
                  <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                    <Search className="w-6 h-6" />
                  </div>
                  <CardTitle className="text-lg group-hover:text-primary transition-colors">
                    AI Detection Guide
                  </CardTitle>
                  <CardDescription>
                    Understand how Turnitin and other detection tools work
                  </CardDescription>
                </CardHeader>
              </Card>
            </Link>

            <Link to="/citing-ai" className="group">
              <Card className="h-full hover:shadow-lg transition-all hover:border-primary/50">
                <CardHeader>
                  <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                    <Quote className="w-6 h-6" />
                  </div>
                  <CardTitle className="text-lg group-hover:text-primary transition-colors">
                    Citing AI Guide
                  </CardTitle>
                  <CardDescription>
                    APA, MLA, Chicago formats for citing AI tools
                  </CardDescription>
                </CardHeader>
              </Card>
            </Link>

            <Link to="/ai-literature-review" className="group">
              <Card className="h-full hover:shadow-lg transition-all hover:border-primary/50">
                <CardHeader>
                  <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                    <BookOpen className="w-6 h-6" />
                  </div>
                  <CardTitle className="text-lg group-hover:text-primary transition-colors">
                    AI for Literature Reviews
                  </CardTitle>
                  <CardDescription>
                    Using AI tools ethically for systematic searches
                  </CardDescription>
                </CardHeader>
              </Card>
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-muted-foreground">
              Common questions about AI use in dissertations
            </p>
          </div>

          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`} className="bg-card rounded-lg border px-6">
                <AccordionTrigger className="text-left hover:no-underline py-6">
                  <span className="font-semibold">{faq.question}</span>
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-6">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 px-4 bg-gradient-to-r from-navy via-navy-light to-navy">
        <div className="container mx-auto max-w-4xl text-center text-white">
          <h2 className="text-3xl font-bold mb-4">Need Expert Guidance?</h2>
          <p className="text-white/80 mb-8 max-w-2xl mx-auto">
            Our dissertation experts can help you navigate AI policies and ensure 
            your work meets all academic integrity requirements.
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <Button asChild size="lg" variant="secondary">
              <Link to="/consultation">
                Book Free Consultation
                <ArrowRight className="w-4 h-4 ml-2" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="glass">
              <Link to="/services">
                View Our Services
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default AIAcademiaHub;
